# Generated by Django 5.2.13 on 2026-09-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(default='New Chat', max_length=30),
        ),
    ]
