# Generated by Django 5.2.13 on 2026-09-18 18:47

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='system_prompt',
            field=models.TextField(default=users.models.read_system_prompt, max_length=3000),
        ),
    ]
