# Generated by Django 5.2.13 on 2026-09-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_system_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_message_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
